services:
  - type: web
    name: omipdf
    runtime: node
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
